package com.lw.productunit.entity;

import java.util.HashMap;
import java.util.Map;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.apache.commons.lang3.StringUtils;

import com.lw.core.entity.BaseEntity;

/**
 * Brand generated by hbm2java
 */
@Entity
@Table(name = "brand", catalog = "mall")
public class Brand extends BaseEntity {

	private static final long serialVersionUID = -3188459327265975714L;
	
	private String name;
	private String enName;
	private String logoBigUrl;
	private String logoSamllUrl;
	private String description;
	
	//private Set<Product> products = new HashSet<Product>(0);

	public Map<String, String> validation(){
		Map<String, String> map = new HashMap<String, String>();
		if(StringUtils.isBlank(name)){
			map.put("neme", "品牌名不能为空");
		}
		if(StringUtils.isBlank(logoBigUrl)){
			map.put("logoBigUrl", "品牌logo名不能为空");
		}
		return map;
	};
	
	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "enName", length = 30)
	public String getEnName() {
		return this.enName;
	}

	public void setEnName(String enName) {
		this.enName = enName;
	}

	@Column(name = "logoBigUrl", length = 100)
	public String getLogoBigUrl() {
		return this.logoBigUrl;
	}

	public void setLogoBigUrl(String logoBigUrl) {
		this.logoBigUrl = logoBigUrl;
	}

	@Column(name = "logoSamllUrl", length = 100)
	public String getLogoSamllUrl() {
		return this.logoSamllUrl;
	}

	public void setLogoSamllUrl(String logoSamllUrl) {
		this.logoSamllUrl = logoSamllUrl;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "brand")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}*/

}
