package com.lw.productunit.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.lw.core.entity.BaseEntity;

/**
 * Brand generated by hbm2java
 */
@Entity
@Table(name = "brand", catalog = "mall")
public class Brand extends BaseEntity implements java.io.Serializable {

	private String name;
	private String enName;
	private String logoBigUrl;
	private String logoSamllUrl;
	private String description;
	private Set<Product> products = new HashSet<Product>(0);

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "enName", length = 30)
	public String getEnName() {
		return this.enName;
	}

	public void setEnName(String enName) {
		this.enName = enName;
	}

	@Column(name = "logoBigUrl", length = 100)
	public String getLogoBigUrl() {
		return this.logoBigUrl;
	}

	public void setLogoBigUrl(String logoBigUrl) {
		this.logoBigUrl = logoBigUrl;
	}

	@Column(name = "logoSamllUrl", length = 100)
	public String getLogoSamllUrl() {
		return this.logoSamllUrl;
	}

	public void setLogoSamllUrl(String logoSamllUrl) {
		this.logoSamllUrl = logoSamllUrl;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "brand")
	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
