package com.lw.productunit.entity;

import java.util.Map;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.lw.core.entity.BaseEntity;

/**
 * Commodity2specitem generated by hbm2java
 */
@Entity
@Table(name = "commodity2specItem", catalog = "mall")
public class Commodity2specitem extends BaseEntity {

	private static final long serialVersionUID = 2349824193557502044L;
	
	private Specitem specitem;
	private Commodity commodity;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "specItemId")
	public Specitem getSpecitem() {
		return this.specitem;
	}

	public void setSpecitem(Specitem specitem) {
		this.specitem = specitem;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "commodityId")
	public Commodity getCommodity() {
		return this.commodity;
	}

	public void setCommodity(Commodity commodity) {
		this.commodity = commodity;
	}

	@Override
	public Map<String, String> validation() {
		// TODO Auto-generated method stub
		return null;
	}
	
}
