package com.lw.productunit.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import com.lw.core.entity.BaseEntity;

/**
 * Commodity generated by hbm2java
 */
@Entity
@Table(name = "commodity", catalog = "mall")
public class Commodity extends BaseEntity implements java.io.Serializable {

	private String sku;
	private String title;
	private String subtitle;
	private long salePrice;
	private long costPrice;
	private String mainPicture;
	private String htmlDescription;
	private Set commodity2specitems = new HashSet(0);
	private Set commodity2propertyitems = new HashSet(0);

	@Column(name = "sku", nullable = false, length = 30)
	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	@Column(name = "title", nullable = false, length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "subtitle", length = 100)
	public String getSubtitle() {
		return this.subtitle;
	}

	public void setSubtitle(String subtitle) {
		this.subtitle = subtitle;
	}

	@Column(name = "salePrice", nullable = false, precision = 10, scale = 0)
	public long getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(long salePrice) {
		this.salePrice = salePrice;
	}

	@Column(name = "costPrice", nullable = false, precision = 10, scale = 0)
	public long getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(long costPrice) {
		this.costPrice = costPrice;
	}

	@Column(name = "mainPicture", nullable = false, length = 100)
	public String getMainPicture() {
		return this.mainPicture;
	}

	public void setMainPicture(String mainPicture) {
		this.mainPicture = mainPicture;
	}

	@Column(name = "htmlDescription", length = 16777215)
	public String getHtmlDescription() {
		return this.htmlDescription;
	}

	public void setHtmlDescription(String htmlDescription) {
		this.htmlDescription = htmlDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commodity")
	public Set getCommodity2specitems() {
		return this.commodity2specitems;
	}

	public void setCommodity2specitems(Set commodity2specitems) {
		this.commodity2specitems = commodity2specitems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commodity")
	public Set getCommodity2propertyitems() {
		return this.commodity2propertyitems;
	}

	public void setCommodity2propertyitems(Set commodity2propertyitems) {
		this.commodity2propertyitems = commodity2propertyitems;
	}

}
