package com.lw.productunit.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import com.lw.core.entity.BaseEntity;

/**
 * Commodity2specitem generated by hbm2java
 */
@Entity
@Table(name = "commodity2specitem", catalog = "mall")
public class Commodity2specitem extends BaseEntity implements java.io.Serializable {

	private Specitem specitem;
	private Commodity commodity;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "specItemId")
	public Specitem getSpecitem() {
		return this.specitem;
	}

	public void setSpecitem(Specitem specitem) {
		this.specitem = specitem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commodityId")
	public Commodity getCommodity() {
		return this.commodity;
	}

	public void setCommodity(Commodity commodity) {
		this.commodity = commodity;
	}
	
}
