package com.lw.productunit.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Propertyitem generated by hbm2java
 */
@Entity
@Table(name = "propertyitem", catalog = "mall")
public class Propertyitem implements java.io.Serializable {

	private Property property;
	private String itemName;
	private Set commodity2propertyitems = new HashSet(0);


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "propertyId")
	public Property getProperty() {
		return this.property;
	}

	public void setProperty(Property property) {
		this.property = property;
	}

	@Column(name = "itemName", nullable = false, length = 30)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "propertyitem")
	public Set getCommodity2propertyitems() {
		return this.commodity2propertyitems;
	}

	public void setCommodity2propertyitems(Set commodity2propertyitems) {
		this.commodity2propertyitems = commodity2propertyitems;
	}

}
