package com.lw.productunit.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Property generated by hbm2java
 */
@Entity
@Table(name = "property", catalog = "mall")
public class Property implements java.io.Serializable {

	private Category category;
	private String name;
	private Set propertyitems = new HashSet(0);

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoryId")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "property")
	public Set getPropertyitems() {
		return this.propertyitems;
	}

	public void setPropertyitems(Set propertyitems) {
		this.propertyitems = propertyitems;
	}

}
