package com.lw.productunit.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Specitem generated by hbm2java
 */
@Entity
@Table(name = "specitem", catalog = "mall")
public class Specitem implements java.io.Serializable {

	private Spec spec;
	private String itemName;
	private Set commodity2specitems = new HashSet(0);

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "specId")
	public Spec getSpec() {
		return this.spec;
	}

	public void setSpec(Spec spec) {
		this.spec = spec;
	}

	@Column(name = "itemName", nullable = false, length = 30)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "specitem")
	public Set getCommodity2specitems() {
		return this.commodity2specitems;
	}

	public void setCommodity2specitems(Set commodity2specitems) {
		this.commodity2specitems = commodity2specitems;
	}

}
