package com.lw.productunit.entity;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.lw.core.entity.BaseEntity;

/**
 * Specitem generated by hbm2java
 */
@Entity
@Table(name = "specItem", catalog = "mall")
public class Specitem extends BaseEntity {

	private static final long serialVersionUID = 5392198178046505034L;
	
	private Spec spec;
	private String itemName;
	private Set<Commodity2specitem> commodity2specitems = new HashSet<Commodity2specitem>(0);

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "specId")
	public Spec getSpec() {
		return this.spec;
	}

	public void setSpec(Spec spec) {
		this.spec = spec;
	}

	@Column(name = "itemName", nullable = false, length = 30)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "specitem")
	public Set<Commodity2specitem> getCommodity2specitems() {
		return this.commodity2specitems;
	}

	public void setCommodity2specitems(Set<Commodity2specitem> commodity2specitems) {
		this.commodity2specitems = commodity2specitems;
	}

	@Override
	public Map<String, String> validation() {
		// TODO Auto-generated method stub
		return null;
	}

}
